name: Download and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  upload-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          curl -L "https://downloads.claude.ai/claude-code-releases/2.1.119/linux-x64/claude" -o claude

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: claude
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
