name: Download and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  upload-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          curl -L "https://coqui.gateway.scarf.sh/v0.10.1_models/tts_models--fa--custom--glow-tts.zip" -o tts_models--fa--custom--glow-tts.zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: tts_models--fa--custom--glow-tts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
