name: Download and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  upload-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          curl -L "https://huggingface.co/OpenMOSS-Team/MOSS-TTS-Nano-100M/resolve/main/tokenizer.model?download=true" -o tokenizer.model

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: tokenizer.model
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
